version: "3"
services:
  producer:
    build: ./producer-service
    ports:
      - "8083:8083"

  consumer:
    build: ./consumer-service
    ports:
      - "8080:8080"
    depends_on:
      - producer-service
 